# NOTE! This is a sample file, it's only here for documentation purposes.

baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

theme = "ultimate-hugo"
staticDir = "static"

DefaultContentLanguage = "en"
[languages]
  [languages.en]
    languageCode = "en-us"
    weight = 1
  [languages.es]
    languageCode = "es"
    weight = 2

[params.integrations]
  gacode = ""
  jivoid = ""
  privyid = ""